// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Tone = require("tone");

var synth = new Tone.Synth();

function startSynth(param) {
  return Tone.start().then(function (param) {
              synth.connect(synth.context.destination);
              
            });
}

function stopSynth(param) {
  return Tone.start().then(function (param) {
              synth.disconnect(synth.context.destination);
              
            });
}

function triggerNote(note) {
  synth.triggerAttack(note);
  
}

exports.synth = synth;
exports.startSynth = startSynth;
exports.stopSynth = stopSynth;
exports.triggerNote = triggerNote;
/* synth Not a pure module */
