// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");

function Button$PlayNote(Props) {
  var children = Props.children;
  var onClick = Props.onClick;
  return React.createElement("button", {
              className: "px-6 py-2 bg-accent font-bold text-current border-dark border-4 text-lg w-full cursor-pointer",
              onClick: onClick
            }, children);
}

var PlayNote = {
  make: Button$PlayNote
};

function Button$Unmute(Props) {
  var children = Props.children;
  var onClick = Props.onClick;
  var onMouseDown = Props.onMouseDown;
  return React.createElement("button", {
              className: "px-6 py-2 bg-accent font-bold text-current border-dark border-4 text-lg w-full cursor-pointer",
              onClick: onClick,
              onMouseDown: (function (param) {
                  if (onMouseDown !== undefined) {
                    return Curry._1(onMouseDown, undefined);
                  }
                  
                })
            }, children);
}

var Unmute = {
  make: Button$Unmute
};

exports.PlayNote = PlayNote;
exports.Unmute = Unmute;
/* react Not a pure module */
