// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Navbar = require("./Navbar.bs.js");

function Layout(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: "flex flex-grow relative w-full"
            }, React.createElement(Navbar.make, {}), children);
}

var make = Layout;

exports.make = make;
/* react Not a pure module */
