// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var RescriptReactRouter = require("@rescript/react/src/RescriptReactRouter.bs.js");

function Menu(Props) {
  var onClick = Props.onClick;
  return React.createElement("ul", {
              className: "currentColor font-semibold flex flex-col gap-4"
            }, React.createElement("li", {
                  className: "cursor-pointer text-accent hover:text-dark",
                  onClick: (function (param) {
                      return Curry._1(onClick, RescriptReactRouter.push("/"));
                    })
                }, "Basic"), React.createElement("li", {
                  className: "cursor-pointer text-accent hover:text-dark",
                  onClick: (function (param) {
                      return Curry._1(onClick, RescriptReactRouter.push("/free"));
                    })
                }, "Free"));
}

var make = Menu;

exports.make = make;
/* react Not a pure module */
