// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Menu = require("./Menu.bs.js");
var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var Ri = require("react-icons/ri");

function Navbar(Props) {
  var match = React.useState(function () {
        return false;
      });
  var setIsOpen = match[1];
  var isOpen = match[0];
  var toggle = function (param) {
    return Curry._1(setIsOpen, (function (isOpen) {
                  return !isOpen;
                }));
  };
  return React.createElement("div", undefined, React.createElement("div", {
                  className: "fixed transition-opacity duration-150 text-black w-screen h-screen transform left-0 flex justify-center items-center text-2xl z-10 " + (
                    isOpen ? "translate-x-0 opacity-100 bg-light" : "translate-x-full opacity-0 bg-light"
                  )
                }, React.createElement(Menu.make, {
                      onClick: toggle
                    })), React.createElement("div", {
                  className: "bajs bottom-0 right-0 flex items-center justify-center z-20"
                }, React.createElement("div", {
                      className: "fixed bottom-10 right-10 w-20 h-20 bg-gray-500 rounded-full flex items-center justify-center z-50 " + (
                        isOpen ? "text-dark transition-colors duration-150" : "text-accentlight "
                      ),
                      onClick: (function (param) {
                          return Curry._1(setIsOpen, (function (isOpen) {
                                        return !isOpen;
                                      }));
                        })
                    }, React.createElement(Ri.RiMenu5Fill, {
                          size: "48"
                        }))));
}

var make = Navbar;

exports.make = make;
/* Menu Not a pure module */
