// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Free = require("./Free.bs.js");
var Tone = require("./bindings/Tone.bs.js");
var Basic = require("./Basic.bs.js");
var Curry = require("rescript/lib/js/curry.js");
var State = require("./State.bs.js");
var React = require("react");
var Layout = require("./components/Layout.bs.js");
var RescriptReactRouter = require("@rescript/react/src/RescriptReactRouter.bs.js");

function App(Props) {
  var url = RescriptReactRouter.useUrl(undefined, undefined);
  var match = React.useState(function () {
        return State.initialState;
      });
  var setState = match[1];
  var state = match[0];
  var onPlayNote = function (note) {
    var match = state.userState;
    if (match) {
      return Tone.triggerNote(note);
    } else {
      Tone.startSynth(undefined).then(function (param) {
            Curry._1(setState, (function (state) {
                    return {
                            userState: /* HasInteracted */1,
                            isPlaying: state.isPlaying
                          };
                  }));
            return Tone.triggerNote(note);
          });
      return ;
    }
  };
  var onUnmute = function (param) {
    Tone.startSynth(undefined).then(function (param) {
          return Curry._1(setState, (function (state) {
                        return {
                                userState: state.userState,
                                isPlaying: true
                              };
                      }));
        });
    
  };
  var onMute = function (param) {
    Tone.stopSynth(undefined).then(function (param) {
          return Curry._1(setState, (function (state) {
                        return {
                                userState: state.userState,
                                isPlaying: false
                              };
                      }));
        });
    
  };
  var triggerAttack = function (note) {
    console.log(note);
    return Tone.triggerNote(note);
  };
  var onUserInteraction = function (param) {
    return Curry._1(setState, (function (state) {
                  return {
                          userState: /* HasInteracted */1,
                          isPlaying: state.isPlaying
                        };
                }));
  };
  var match$1 = url.path;
  var tmp;
  tmp = match$1 ? (
      match$1.hd === "free" && !match$1.tl ? React.createElement(Free.make, {
              userState: state.userState,
              onUserInteraction: onUserInteraction,
              onMute: onMute,
              onUnmute: onUnmute,
              isPlaying: state.isPlaying,
              triggerAttack: triggerAttack
            }) : React.createElement("div", undefined)
    ) : React.createElement(Basic.make, {
          onPlayNote: onPlayNote
        });
  return React.createElement("main", {
              className: "flex flex-col items-center h-screen w-screen overflow-hidden"
            }, React.createElement(Layout.make, {
                  children: tmp
                }));
}

var make = App;

exports.make = make;
/* Free Not a pure module */
