// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var Button = require("./components/Button.bs.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");

var defaultTuning = [
  "E2",
  "A2",
  "D3",
  "G3",
  "B3",
  "E4"
];

function Basic(Props) {
  var onPlayNote = Props.onPlayNote;
  return React.createElement("div", {
              className: "w-full h-full flex justify-center items-center text-light px-4"
            }, React.createElement("div", {
                  className: "flex flex-grow flex-col justify-center items-center max-w-sm gap-6 w-full"
                }, Belt_Array.map(defaultTuning, (function (note) {
                        return React.createElement(Button.PlayNote.make, {
                                    children: note,
                                    onClick: (function (param) {
                                        return Curry._1(onPlayNote, note);
                                      }),
                                    key: note
                                  });
                      }))));
}

var make = Basic;

exports.defaultTuning = defaultTuning;
exports.make = make;
/* react Not a pure module */
