// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var initialState = {
  userState: /* HasNotInteraced */0,
  isPlaying: false
};

exports.initialState = initialState;
/* No side effect */
